BATCH_SIZE = 8
EPOCHS = 50
RESAMPLING_F = 24000
INIT_LR = 1e-4
NUM_BANDS = 26
PATH_DATASET = "/home/jonas/CLionProjects/soundLocalizer/python-scripts/analysis/output_dataset.csv"
LENGTH_AUDIO = 1000
TEST_SUBJECTS = [8, 21]
FEATURES = 'gcc-phat'